### ID/Password 로그인 테스트
POST {{host}}/login
Content-Type: application/json

{
  "email": "keehwan@weversecompany.com",
  "password": "test1234"
}

> {%
    client.global.set("Authorization", response.headers.valueOf("Authorization"));
    client.log("access token : " + client.global.get("Authorization"));
%}

### 리프레쉬 토큰을 이용 토큰 재발급
POST {{host}}/renew
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiUkVGUkVTSCIsInVzZXJuYW1lIjoia2VlaHdhbkB3ZXZlcnNlY29tcGFueS5jb20iLCJpYXQiOjE3MjUzNDEzMDYsImV4cCI6MTcyNzkzMzMwNn0.u2C52PaHKXuVPu9XXOWEJTUsV7fnAh8aLlWzrzrmFP8"
}

> {%
client.global.set("Authorization", 'Bearer ' + response.body.data);
client.log("access token : " + client.global.get("Authorization"));
%}


### 토큰을 expire 시킨다.
POST {{host}}/logout
Content-Type: application/json
Authorization: {{Authorization}}

