### 인증번호를 요청한다.
POST {{host}}/api/v1/verifications/phone
Content-Type: application/json
Authorization: {{Authorization}}

{
  "phone_number": "01039960399"
}

### 인증번호를 확인한다.
PATCH {{host}}/api/v1/verifications/phone/verify-code
Content-Type: application/json
Authorization: {{Authorization}}

{
  "token": "0a5a8bf4a86a433f84188411b3a8fc11",
  "code": "885061"
}

